language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - coverage run app/test/v1/test_v1.py

after_success:
  - coveralls
  - coverage report

#safelist
branches:
  only:
    - develop